version: 2.1

jobs:
  build:
      docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install pip3 packages 
          command: |
            python3 -m venv env
            .env/bin/activate
            pip3 install -r requirements.txt

      - run:
          name: Test with pytest
          command: |
            . venv/bin/activate
            pytest -v

