# Generated by Django 4.1.5 on 2023-02-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_transcripts", models.URLField(blank=True)),
                ("skills", models.TextField(blank=True)),
                ("Licenses", models.FileField(blank=True, upload_to="")),
                ("certifications", models.FileField(blank=True, upload_to="")),
                ("languages", models.CharField(blank=True, max_length=99)),
            ],
        ),
    ]
