# Generated by Django 4.1.5 on 2023-02-08 08:49

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="location",
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
