# Generated by Django 4.1.5 on 2023-01-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_transcripts", models.URLField(blank=True)),
                ("skills", models.TextField(blank=True)),
                ("Licenses", models.FileField(blank=True, upload_to="")),
                ("certifications", models.FileField(blank=True, upload_to="")),
                ("languages", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="JobPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("job_types", models.CharField(blank=True, max_length=100)),
                ("work_environment", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="student",
            name="academic_transcripts",
        ),
        migrations.AddField(
            model_name="student",
            name="cover_letter",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="student",
            name="location",
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="student",
            name="resume",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
