# Generated by Django 4.1.5 on 2023-02-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_education_jobpreferences_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="JobPreferences",
        ),
    ]
